#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, please define the SHELL environment variable to point to it.
#
#   (2) All the variables in this script are set by a "configure" stage. In
#       particular, the name of the script is used to locate the Gradle
#       installation, so don't rename this script.
#
#   Important for patching:
#
#   (1) This script is generated from the template in
#       tools/internal/templates/startScripts/posixTemplate.txt
#       within the Gradle project.
#
#   (2) Please review the test cases in
#       subprojects/plugins/src/test/groovy/org/gradle/api/tasks/WriteExecStartScripts*Test.groovy
#       within the Gradle project.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# Change from the directory of the app to the directory of the script
cd "${APP_HOME:-./}"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo >&2 "$*"
}

die () {
    echo >&2 "$*"
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && [ "$MAX_FD" != "unlimited" ] ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit: $MAX_FD"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit: $MAX_FD"
    esac
fi

# For Darwin, add options to make large stacks work, and use a thread stack size of 1024k.
if "$darwin" ; then
    # Must work also under -n (no-echo)
    # shellcheck disable=SC2039
    while [ $# -gt 0 ] ; do
        if [ "$1" = "-Xdock:name="* ] ; then
            DOCK_NAME=$1
            shift
            continue
        fi
        if [ "$1" = "-Xdock:icon="* ] ; then
            DOCK_ICON=$1
            shift
            continue
        fi
        break
    done
    # shellcheck disable=SC2039
    exec "$JAVACMD" \
        -Xss1024k \
        -XX:MaxMetaspaceSize=256m \
        -XX:ThreadStackSize=1024k \
        -XX:+UseSerialGC \
        -Xms256m -Xmx512m \
        ${DOCK_NAME+"$DOCK_NAME"} \
        ${DOCK_ICON+"$DOCK_ICON"} \
        -jar "$CLASSPATH" \
        "$@"
else
    # shellcheck disable=SC2039
    exec "$JAVACMD" \
        -XX:MaxMetaspaceSize=256m \
        -Xms256m -Xmx512m \
        -jar "$CLASSPATH" \
        "$@"
fi